--- #YAML:1.0
 name: Captcha-Stateless-Text
 abstract: stateless, text-based CAPTCHAs
 version: 0.3
 author:
   - Lester Hightower <hightowe@cpan.org>
 license: perl
 distribution_type: module
 requires:
   - Lingua::EN::Nums2Words
   - Try::Tiny
   - Crypt::Mode::CBC
   - JSON
 recommends:
 build_requires:
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: Module::Build version 0.20
