--- #YAML:1.0
 name: Captcha-Stateless-Text
 abstract: stateless, text-based CAPTCHAs
 version: 0.5
 author:
   - Lester Hightower <hightowe@cpan.org>
 license: perl
 distribution_type: module
 requires:
   # Perl >= v5.20 needed for feature "signatures"
   perl: '5.020000'
   Sub::Util: 0
   Lingua::EN::Nums2Words: 0
   Try::Tiny: 0
   Crypt::Mode::CBC: 0
   JSON: 0
 recommends:
 build_requires:
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 resources:
   license: http://dev.perl.org/licenses/
   bugtracker: https://github.com/hightowe/Captcha-Stateless-Text/issues
   repository: https://github.com/hightowe/Captcha-Stateless-Text
 generated_by: Module::Build version 0.20
